name: dot_flutter_sdk_example
description: Demonstrates how to use the DOT Flutter SDK.
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  uses-material-design: true
  assets:
    - assets/

dependencies:
  dot_document: ^0.10.3
  dot_face_core: ^0.10.3
  dot_face_detection_fast: ^0.10.3
  dot_face_expression_neutral: ^0.10.3
  dot_nfc: ^0.10.3
  flutter:
    sdk: flutter
  path_provider: ^2.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
